name: flyingwolf
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modal_progress_hud: ^0.1.3
  fluttertoast: ^3.1.0

  cupertino_icons: ^0.1.3
  http: 0.12.2
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
